// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_types.proto

public final class MessageTypes {
  private MessageTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TransportEnvelope extends
      com.google.protobuf.GeneratedMessage {
    // Use TransportEnvelope.newBuilder() to construct.
    private TransportEnvelope() {
      initFields();
    }
    private TransportEnvelope(boolean noInit) {}
    
    private static final TransportEnvelope defaultInstance;
    public static TransportEnvelope getDefaultInstance() {
      return defaultInstance;
    }
    
    public TransportEnvelope getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageTypes.internal_static_TransportEnvelope_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageTypes.internal_static_TransportEnvelope_fieldAccessorTable;
    }
    
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      CreateFileRequest(0, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return CreateFileRequest;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageTypes.TransportEnvelope.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MessageType[] VALUES = {
        CreateFileRequest, 
      };
      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        MessageTypes.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:TransportEnvelope.MessageType)
    }
    
    // required .TransportEnvelope.MessageType message_type = 1;
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
    private boolean hasMessageType;
    private MessageTypes.TransportEnvelope.MessageType messageType_;
    public boolean hasMessageType() { return hasMessageType; }
    public MessageTypes.TransportEnvelope.MessageType getMessageType() { return messageType_; }
    
    // required bytes message_bytes = 2;
    public static final int MESSAGE_BYTES_FIELD_NUMBER = 2;
    private boolean hasMessageBytes;
    private com.google.protobuf.ByteString messageBytes_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessageBytes() { return hasMessageBytes; }
    public com.google.protobuf.ByteString getMessageBytes() { return messageBytes_; }
    
    private void initFields() {
      messageType_ = MessageTypes.TransportEnvelope.MessageType.CreateFileRequest;
    }
    public final boolean isInitialized() {
      if (!hasMessageType) return false;
      if (!hasMessageBytes) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessageType()) {
        output.writeEnum(1, getMessageType().getNumber());
      }
      if (hasMessageBytes()) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessageType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getMessageType().getNumber());
      }
      if (hasMessageBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static MessageTypes.TransportEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageTypes.TransportEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.TransportEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageTypes.TransportEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.TransportEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageTypes.TransportEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.TransportEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessageTypes.TransportEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessageTypes.TransportEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageTypes.TransportEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageTypes.TransportEnvelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private MessageTypes.TransportEnvelope result;
      
      // Construct using MessageTypes.TransportEnvelope.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new MessageTypes.TransportEnvelope();
        return builder;
      }
      
      protected MessageTypes.TransportEnvelope internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new MessageTypes.TransportEnvelope();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageTypes.TransportEnvelope.getDescriptor();
      }
      
      public MessageTypes.TransportEnvelope getDefaultInstanceForType() {
        return MessageTypes.TransportEnvelope.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public MessageTypes.TransportEnvelope build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private MessageTypes.TransportEnvelope buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public MessageTypes.TransportEnvelope buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        MessageTypes.TransportEnvelope returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageTypes.TransportEnvelope) {
          return mergeFrom((MessageTypes.TransportEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessageTypes.TransportEnvelope other) {
        if (other == MessageTypes.TransportEnvelope.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasMessageBytes()) {
          setMessageBytes(other.getMessageBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              MessageTypes.TransportEnvelope.MessageType value = MessageTypes.TransportEnvelope.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setMessageType(value);
              }
              break;
            }
            case 18: {
              setMessageBytes(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required .TransportEnvelope.MessageType message_type = 1;
      public boolean hasMessageType() {
        return result.hasMessageType();
      }
      public MessageTypes.TransportEnvelope.MessageType getMessageType() {
        return result.getMessageType();
      }
      public Builder setMessageType(MessageTypes.TransportEnvelope.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMessageType = true;
        result.messageType_ = value;
        return this;
      }
      public Builder clearMessageType() {
        result.hasMessageType = false;
        result.messageType_ = MessageTypes.TransportEnvelope.MessageType.CreateFileRequest;
        return this;
      }
      
      // required bytes message_bytes = 2;
      public boolean hasMessageBytes() {
        return result.hasMessageBytes();
      }
      public com.google.protobuf.ByteString getMessageBytes() {
        return result.getMessageBytes();
      }
      public Builder setMessageBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageBytes = true;
        result.messageBytes_ = value;
        return this;
      }
      public Builder clearMessageBytes() {
        result.hasMessageBytes = false;
        result.messageBytes_ = getDefaultInstance().getMessageBytes();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:TransportEnvelope)
    }
    
    static {
      defaultInstance = new TransportEnvelope(true);
      MessageTypes.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TransportEnvelope)
  }
  
  public static final class CreateFileRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateFileRequest.newBuilder() to construct.
    private CreateFileRequest() {
      initFields();
    }
    private CreateFileRequest(boolean noInit) {}
    
    private static final CreateFileRequest defaultInstance;
    public static CreateFileRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateFileRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageTypes.internal_static_CreateFileRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageTypes.internal_static_CreateFileRequest_fieldAccessorTable;
    }
    
    // required string file_name = 1;
    public static final int FILE_NAME_FIELD_NUMBER = 1;
    private boolean hasFileName;
    private java.lang.String fileName_ = "";
    public boolean hasFileName() { return hasFileName; }
    public java.lang.String getFileName() { return fileName_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasFileName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFileName()) {
        output.writeString(1, getFileName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFileName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFileName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static MessageTypes.CreateFileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageTypes.CreateFileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.CreateFileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageTypes.CreateFileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.CreateFileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageTypes.CreateFileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.CreateFileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessageTypes.CreateFileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessageTypes.CreateFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageTypes.CreateFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageTypes.CreateFileRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private MessageTypes.CreateFileRequest result;
      
      // Construct using MessageTypes.CreateFileRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new MessageTypes.CreateFileRequest();
        return builder;
      }
      
      protected MessageTypes.CreateFileRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new MessageTypes.CreateFileRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageTypes.CreateFileRequest.getDescriptor();
      }
      
      public MessageTypes.CreateFileRequest getDefaultInstanceForType() {
        return MessageTypes.CreateFileRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public MessageTypes.CreateFileRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private MessageTypes.CreateFileRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public MessageTypes.CreateFileRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        MessageTypes.CreateFileRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageTypes.CreateFileRequest) {
          return mergeFrom((MessageTypes.CreateFileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessageTypes.CreateFileRequest other) {
        if (other == MessageTypes.CreateFileRequest.getDefaultInstance()) return this;
        if (other.hasFileName()) {
          setFileName(other.getFileName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFileName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string file_name = 1;
      public boolean hasFileName() {
        return result.hasFileName();
      }
      public java.lang.String getFileName() {
        return result.getFileName();
      }
      public Builder setFileName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFileName = true;
        result.fileName_ = value;
        return this;
      }
      public Builder clearFileName() {
        result.hasFileName = false;
        result.fileName_ = getDefaultInstance().getFileName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CreateFileRequest)
    }
    
    static {
      defaultInstance = new CreateFileRequest(true);
      MessageTypes.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CreateFileRequest)
  }
  
  public static final class CreateFileResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateFileResponse.newBuilder() to construct.
    private CreateFileResponse() {
      initFields();
    }
    private CreateFileResponse(boolean noInit) {}
    
    private static final CreateFileResponse defaultInstance;
    public static CreateFileResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateFileResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageTypes.internal_static_CreateFileResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageTypes.internal_static_CreateFileResponse_fieldAccessorTable;
    }
    
    // required bool ok = 1;
    public static final int OK_FIELD_NUMBER = 1;
    private boolean hasOk;
    private boolean ok_ = false;
    public boolean hasOk() { return hasOk; }
    public boolean getOk() { return ok_; }
    
    // required uint32 status_code = 2;
    public static final int STATUS_CODE_FIELD_NUMBER = 2;
    private boolean hasStatusCode;
    private int statusCode_ = 0;
    public boolean hasStatusCode() { return hasStatusCode; }
    public int getStatusCode() { return statusCode_; }
    
    // optional string status_msg = 3;
    public static final int STATUS_MSG_FIELD_NUMBER = 3;
    private boolean hasStatusMsg;
    private java.lang.String statusMsg_ = "";
    public boolean hasStatusMsg() { return hasStatusMsg; }
    public java.lang.String getStatusMsg() { return statusMsg_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasOk) return false;
      if (!hasStatusCode) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOk()) {
        output.writeBool(1, getOk());
      }
      if (hasStatusCode()) {
        output.writeUInt32(2, getStatusCode());
      }
      if (hasStatusMsg()) {
        output.writeString(3, getStatusMsg());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOk()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getOk());
      }
      if (hasStatusCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getStatusCode());
      }
      if (hasStatusMsg()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getStatusMsg());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static MessageTypes.CreateFileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageTypes.CreateFileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.CreateFileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MessageTypes.CreateFileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.CreateFileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageTypes.CreateFileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MessageTypes.CreateFileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessageTypes.CreateFileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MessageTypes.CreateFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MessageTypes.CreateFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageTypes.CreateFileResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private MessageTypes.CreateFileResponse result;
      
      // Construct using MessageTypes.CreateFileResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new MessageTypes.CreateFileResponse();
        return builder;
      }
      
      protected MessageTypes.CreateFileResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new MessageTypes.CreateFileResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageTypes.CreateFileResponse.getDescriptor();
      }
      
      public MessageTypes.CreateFileResponse getDefaultInstanceForType() {
        return MessageTypes.CreateFileResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public MessageTypes.CreateFileResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private MessageTypes.CreateFileResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public MessageTypes.CreateFileResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        MessageTypes.CreateFileResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageTypes.CreateFileResponse) {
          return mergeFrom((MessageTypes.CreateFileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MessageTypes.CreateFileResponse other) {
        if (other == MessageTypes.CreateFileResponse.getDefaultInstance()) return this;
        if (other.hasOk()) {
          setOk(other.getOk());
        }
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasStatusMsg()) {
          setStatusMsg(other.getStatusMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setOk(input.readBool());
              break;
            }
            case 16: {
              setStatusCode(input.readUInt32());
              break;
            }
            case 26: {
              setStatusMsg(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required bool ok = 1;
      public boolean hasOk() {
        return result.hasOk();
      }
      public boolean getOk() {
        return result.getOk();
      }
      public Builder setOk(boolean value) {
        result.hasOk = true;
        result.ok_ = value;
        return this;
      }
      public Builder clearOk() {
        result.hasOk = false;
        result.ok_ = false;
        return this;
      }
      
      // required uint32 status_code = 2;
      public boolean hasStatusCode() {
        return result.hasStatusCode();
      }
      public int getStatusCode() {
        return result.getStatusCode();
      }
      public Builder setStatusCode(int value) {
        result.hasStatusCode = true;
        result.statusCode_ = value;
        return this;
      }
      public Builder clearStatusCode() {
        result.hasStatusCode = false;
        result.statusCode_ = 0;
        return this;
      }
      
      // optional string status_msg = 3;
      public boolean hasStatusMsg() {
        return result.hasStatusMsg();
      }
      public java.lang.String getStatusMsg() {
        return result.getStatusMsg();
      }
      public Builder setStatusMsg(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatusMsg = true;
        result.statusMsg_ = value;
        return this;
      }
      public Builder clearStatusMsg() {
        result.hasStatusMsg = false;
        result.statusMsg_ = getDefaultInstance().getStatusMsg();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CreateFileResponse)
    }
    
    static {
      defaultInstance = new CreateFileResponse(true);
      MessageTypes.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CreateFileResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportEnvelope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransportEnvelope_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateFileRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateFileRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateFileResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateFileResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023message_types.proto\"\206\001\n\021TransportEnvel" +
      "ope\0224\n\014message_type\030\001 \002(\0162\036.TransportEnv" +
      "elope.MessageType\022\025\n\rmessage_bytes\030\002 \002(\014" +
      "\"$\n\013MessageType\022\025\n\021CreateFileRequest\020\001\"&" +
      "\n\021CreateFileRequest\022\021\n\tfile_name\030\001 \002(\t\"I" +
      "\n\022CreateFileResponse\022\n\n\002ok\030\001 \002(\010\022\023\n\013stat" +
      "us_code\030\002 \002(\r\022\022\n\nstatus_msg\030\003 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TransportEnvelope_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TransportEnvelope_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TransportEnvelope_descriptor,
              new java.lang.String[] { "MessageType", "MessageBytes", },
              MessageTypes.TransportEnvelope.class,
              MessageTypes.TransportEnvelope.Builder.class);
          internal_static_CreateFileRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CreateFileRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CreateFileRequest_descriptor,
              new java.lang.String[] { "FileName", },
              MessageTypes.CreateFileRequest.class,
              MessageTypes.CreateFileRequest.Builder.class);
          internal_static_CreateFileResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CreateFileResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CreateFileResponse_descriptor,
              new java.lang.String[] { "Ok", "StatusCode", "StatusMsg", },
              MessageTypes.CreateFileResponse.class,
              MessageTypes.CreateFileResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
